### ISSUE TITLE
Connection Error "Client does not support authentication protocol requested by server; consider upgrading MySQL client"

### ISSUE THREAD

**Issue by bryonjacob** [jaredwray/keyv-mysql#42]
Getting this error on connection to MySQL:

Connection Error Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Object.createConnection (/Users/bryon/working/data.world/api-starters/examples/bryon-test/node_modules/mysql2/promise.js:31:31)
    at /Users/bryon/working/data.world/api-starters/examples/bryon-test/node_modules/@keyv/mysql/src/index.js:17:22
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  message: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlState: '08004'
}

Tracking this down, it seems to be an issue with more recent versions of MySQL, and the `mysql2` connector you're using here was updated to fix this late last year:

https://github.com/sidorares/node-mysql2/issues/991

So, presuming that the driver is otherwise compatible with keyv-mysql, updating to the latest release of `mysql2` should address this issue.

**Comment by jaredwray** [comment]
@bryonjacob - we just updated to latest mysql2 so this should be resolved
